apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 909726553928.dkr.ecr.ap-northeast-1.amazonaws.com/devops-project-frontend:latest
        ports:
        - containerPort: 80
